### ISSUE TITLE
Option to disable virtex on Vagrantfile

### ISSUE THREAD

**Issue by amateo** [PraxisLabs/vagrant-yaml#2]
Is there any option to disable virtex in a virtualbox machine from vagrant?

It would be nice is there was some way to add a configuration like:

```
  c.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
  end
```

as it's done with memory option

**Comment by ergonlogic** [comment]
This project (vagrant-yaml) has been supplanted by vagrant-pirate (https://github.com/PraxisLabs/vagrant-pirate). So, since vagrant-yaml is essentially deprecated/abandoned, I would highly recommend checking out that project, as it improves significantly on vagrant-yaml.

I have taken the liberty of creating an issue in that projec, for this request: thttps://github.com/PraxisLabs/vagrant-pirate/issues/1
